### PR TITLE
Python 3 refactor

### PR DESCRIPTION
**Pull request by thenaturalist**
Saw the Python 3 issue and thought I'd create a PR.
Basic refactoring of the functional python files.  

- PEP8 style
- deleted direct credential variables and added environment variables
- dropped api_key as the new authentication maintained by Mixpanel uses secret only. 

I'm working on a Python3 implementation of the Mixpanel API request code. 
Mixpanel themselves changed their example code. See their version here: 
https://mixpanel.com/site_media/api/v2/mixpanel.py

### CODE REVIEW

**Comment by kimeshan** [comment]
@thenaturalist Awesome stuff, this looks great! Will have a closer look in the morning and then we can merge.

**Comment by thenaturalist** [comment]
@kimeshan happy to help. Not sure if merging makes sense before refactoring the main Mixpanel API data endpoint code as it is still in Python 2 and the `unicode_urlencode` method specifically needs to be rewritten it seems to me. We'd end up with a mix. 

I plan to work on that tonight. Sounds good?

**Comment by thenaturalist** [comment]
@kimeshan update the two Mixpanel API scripts. Should be working. Can you check?

Still open: Adapt the API calls made from the remaining data pulling scripts.

**Comment by kimeshan** [comment]
Okay great work, I'll pull it in and test. Might add some PyTest as well! It needs testing added too :)

**Comment by kimeshan** [comment]
@thenaturalist I've created a dev branch so could you change the base branch of this PR to dev?

**Comment by thenaturalist** [comment]
@kimeshan sorry for the delay, traveling. Changed the base branch. Anything else you need from my side?

**Comment by thenaturalist** [comment]
ping

**Comment by kimeshan** [comment]
@thenaturalist Cool, just merged - will test on dev when I have a chance. Swamped at the moment.

**Pull request merged**
